export const actionTypes = {
 LOGIN_FAILURE:"LOGIN_FAILURE",
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	SIGNIN_FAILURE:"SIGNIN_FAILURE",
	SIGNIN_SUCCESS:"SIGNIN_SUCCESS",
	FETCH_HOUSES:"FETCH_HOUSES",
	UPDATE_HOUSE:"UPDATE_HOUSE",
	DELETE_HOUSE:"DELETE_HOUSE",
	ADD_HOUSE:"ADD_HOUSE",
	ADD_ROOM:"ADD_ROOM",
	ADD_FLOOR:"ADD_FLOOR",
	UPDATE_ROOM:"UPDATE_ROOM",
	DELETE_ROOM:"DELETE_ROOM",
	UPDATE_FLOOR:"UPDATE_FLOOR",
	DELETE_FLOOR:"DELETE_FLOOR"
	,GET_ROOMS:"GET_ROOMS",
	GET_FLOORS:"GET_FLOORS",
	GET_HOUSES:"GET_HOUSES",
	GET_HOUSE:"GET_HOUSE",
	GET_FLOOR:"GET_FLOOR",
	GET_ROOM:"GET_ROOM",
  SET_TOTAL_FLOORS :"SET_TOTAL_FLOORS",
  SET_CURRENT_FLOOR:"SET_CURRENT_FLOOR",
  CLEAR:"CLEAR",
	
	

};
